// these are the releastionships between the proactive controls and the cards
export const proactiveControlRelations = [
  {
    index: 1,
    cards: {
      "data validation & encoding": ["2", "9", "J", "K"],
      authentication: ["2", "8", "K"],
      authorization: ["3", "J", "K"],
      cryptography: ["8", "10", "K"],
      cornucopia: ["2", "K"],
    },
  },
  {
    index: 2,
    cards: {
      "data validation & encoding": ["3", "6", "Q"],
      authentication: ["4", "J"],
      "session management": ["2", "Q"],
      authorization: ["7", "10"],
      cryptography: ["5", "9"],
    },
  },
  {
    index: 3,
    cards: {
      "data validation & encoding": ["4", "7", "10"],
      authentication: ["5", "Q"],
      "session management": ["3", "K"],
      authorization: ["8", "Q"],
      cornucopia: ["3", "J"],
    },
  },
  {
    index: 4,
    cards: {
      "data validation & encoding": ["3", "6", "8", "10", "J"],
      authentication: ["3", "4", "10"],
      authorization: ["2", "4"],
      cryptography: ["3", "4", "5"],
      cornucopia: ["3"],
    },
  },
  {
    index: 5,
    cards: {
      "data validation & encoding": [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "J",
        "Q",
        "K",
      ],
      authentication: ["2", "3", "4", "5", "8", "9", "10", "J", "Q"],
      "session management": [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "J",
        "Q",
        "K",
      ],
      authorization: ["3", "4", "8", "9", "J"],
      cornucopia: ["2", "3", "6", "8", "9", "J", "K"],
    },
  },
  {
    index: 6,
    cards: {
      "data validation & encoding": ["2"],
      authentication: ["9"],
      authorization: ["8", "9"],
      cryptography: ["7", "9"],
      cornucopia: ["6", "8", "10", "J"],
    },
  },
  {
    index: 7,
    cards: {
      "data validation & encoding": ["2", "3", "5", "7", "9", "10", "K"],
      authentication: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "J",
        "Q",
        "K",
      ],
      "session management": ["3", "6", "7", "8", "J", "Q", "K"],
      authorization: ["3", "4", "5", "9"],
      cornucopia: ["2", "5", "8", "9", "K"],
    },
  },
  {
    index: 8,

    cards: {
      "data validation & encoding": [
        "2",
        "3",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "J",
        "Q",
        "K",
      ],
      authentication: ["2", "3", "4", "5", "6", "7", "9", "10", "J", "Q", "K"],
      "session management": [
        "2",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "J",
        "Q",
        "K",
      ],
      authorization: ["3", "5", "8", "9"],
      cryptography: ["3", "J"],
      cornucopia: ["2", "3", "6", "7", "10", "J", "K"],
    },
  },
  {
    index: 9,
    cards: {
      "data validation & encoding": ["3", "4"],
      authentication: ["3"],
      authorization: ["9"],
      cornucopia: ["2", "4", "7", "8", "Q"],
    },
  },
  {
    index: 10,
    cards: {
      "data validation & encoding": ["2", "7", "Q"],
      "session management": ["4", "10"],
      authorization: ["2", "8", "9"],
      cryptography: ["7", "J"],
      cornucopia: ["3", "5", "Q"],
    },
  },
];
